spring:
  application:
    name: mybatis
  datasource:
    hikari:
      ## 最小空闲连接数
      minimum-idle: 2
      ## 连接池最大连接数
      maximum-pool-size: 10
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池名称
      pool-name: MyHikariCP
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 3000
    url: jdbc:mysql://192.168.2.57:3306/highzap_cloud?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
server:
  port: 8888